name: state_repository
publish_to: none

environment: 
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  domain_entities:
    path: ../domain_entities
  equatable: ^2.0.5 
  key_value_storage: 
    path: ../key_value_storage
  uuid: ^4.5.1  
  intl: ^0.19.0
  board_game:
    path: ../features/board_game

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
