analyzer:
  errors:
    use_build_context_synchronously: ignore
    unused_field: ignore
    library_private_types_in_public_api: ignore
    unused_element: ignore
    no_leading_underscores_for_local_identifiers: ignore 
include: package:flutter_lints/flutter.yaml

linter:
  rules: