name: key_value_storage
publish_to: none

environment: 
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  domain_entities:
    path: ../domain_entities
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
